# Generated by Django 5.2.6 on 2026-01-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_viplevel_validity_days_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('other', 'Autre')], default='other', max_length=50),
        ),
    ]
