# Generated by Django 5.2.6 on 2026-01-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usertaskcompletion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='check_in_streak',
            field=models.IntegerField(default=0, verbose_name='Série actuelle'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier Check-in'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('MINING_REWARD', 'Gain Minage'), ('TASK_REWARD', 'Gain Tâche'), ('VIP_PURCHASE', 'Achat VIP'), ('REFERRAL_BONUS', 'Bonus Parrainage'), ('DAILY_CHECKIN', 'Bonus Quotidien')], max_length=20),
        ),
    ]
