# Generated by Django 5.2.6 on 2026-01-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customuser_last_spin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_spin_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='free_spins',
            field=models.IntegerField(default=0, verbose_name='Tours gratuits bonus'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_spin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernier tour de roue'),
        ),
    ]
