# Generated by Django 5.2.6 on 2026-01-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_customuser_last_spin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('other', 'Autre')], default='other', max_length=50),
        ),
    ]
