# Generated by Django 5.2.6 on 2026-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertaskcompletion_screenshot_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to='tasks/proofs/', verbose_name="Capture d'écran"),
        ),
    ]
