# Generated by Django 5.2.6 on 2026-01-16 07:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usertaskcompletion_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_triggered_referral_bonus',
            field=models.BooleanField(default=False, verbose_name='A déjà généré un bonus parrain'),
        ),
        migrations.AddField(
            model_name='viplevel',
            name='referral_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10, verbose_name='Bonus Parrainage (Invitation)'),
        ),
    ]
