# Generated by Django 5.2.6 on 2026-01-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_link_alter_task_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskcompletion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20),
        ),
    ]
