# Generated by Django 5.2.6 on 2026-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customuser_check_in_streak_customuser_last_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP connue'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Inscription'),
        ),
    ]
