# Generated by Django 5.2.6 on 2026-01-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_spin_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier tour de roue'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('MINING_REWARD', 'Gain Minage'), ('TASK_REWARD', 'Gain Tâche'), ('VIP_PURCHASE', 'Achat VIP'), ('REFERRAL_BONUS', 'Bonus Parrainage'), ('DAILY_CHECKIN', 'Bonus Quotidien'), ('SPIN_WIN', 'Roue de la Fortune')], max_length=20),
        ),
    ]
