# Generated by Django 5.2.6 on 2026-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='Validation automatique'),
        ),
        migrations.AlterField(
            model_name='task',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('internal', 'Plateforme'), ('other', 'Autre')], default='other', max_length=50),
        ),
    ]
