# Generated by Django 5.2.6 on 2026-01-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_is_automatic_alter_task_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_image',
            field=models.FileField(blank=True, null=True, upload_to='deposits/proofs/', verbose_name='Preuve de dépôt'),
        ),
    ]
