# Generated by Django 5.2.6 on 2026-01-29 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_transaction_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gains Totaux cumulés'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdrawal_phone_locked',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numéro de retrait verrouillé'),
        ),
    ]
