# Generated by Django 6.0.1 on 2026-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_duration_seconds_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_survey',
            field=models.BooleanField(default=False, verbose_name='Sondage complété'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Centres d'intérêt"),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('trading', 'Trading'), ('dropshipping', 'Dropshipping'), ('content_creation', 'Création de contenu'), ('digital_products', 'Vente de produits digitaux'), ('general', 'Général'), ('other', 'Autre')], default='general', max_length=50, verbose_name='Catégorie'),
        ),
    ]
