# Generated by Django 6.0.1 on 2026-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customuser_has_completed_survey_customuser_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='survey_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Données détaillées du sondage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('trading', 'Trading'), ('dropshipping', 'Dropshipping'), ('content_creation', 'Création de contenu'), ('digital_products', 'Vente de produits digitaux'), ('freelancing', 'Freelancing'), ('sports_betting', 'Paris Sportifs'), ('development', 'Développement & Informatique'), ('graphic_design', 'Design & Multimédia'), ('digital_marketing', 'Marketing Digital'), ('general', 'Général'), ('other', 'Autre')], default='general', max_length=50, verbose_name='Catégorie'),
        ),
    ]
