# Generated by Django 6.0.1 on 2026-03-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customuser_survey_data_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_link_proof',
            field=models.BooleanField(default=False, verbose_name='Nécessite un lien de preuve'),
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='proof_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de preuve'),
        ),
    ]
