# Generated by Django 6.0.1 on 2026-03-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_seen_onboarding',
            field=models.BooleanField(default=False, verbose_name='A vu le tutoriel'),
        ),
    ]
