# Generated by Django 6.0.1 on 2026-05-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_customuser_has_seen_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('OM', 'Orange Money'), ('MOMO', 'MTN MoMo')], max_length=10)),
                ('name', models.CharField(max_length=100, verbose_name='Nom du bénéficiaire')),
                ('number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Méthode de dépôt',
                'verbose_name_plural': 'Méthodes de dépôt',
            },
        ),
        migrations.AddField(
            model_name='usertaskcompletion',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name="Hash de l'image"),
        ),
    ]
