# Generated by Django 6.0.1 on 2026-05-14 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_is_phone_verified_customuser_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Généré par'),
        ),
    ]
