# Generated by Django 6.0.1 on 2026-05-14 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transaction_from_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='Réponse Admin')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('PENDING', 'En cours'), ('CLOSED', 'Fermé')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Support',
                'verbose_name_plural': 'Tickets de Support',
                'ordering': ['-updated_at'],
            },
        ),
    ]
