# Generated by Django 6.0.1 on 2026-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0026_supportticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Empreinte appareil'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['registration_ip', 'last_ip'], name='core_custom_registr_e91dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['referred_by'], name='core_custom_referre_dc6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['device_fingerprint'], name='core_custom_device__df52dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'status', 'created_at'], name='core_transa_user_id_a764c7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='core_transa_created_2964c5_idx'),
        ),
    ]
