# Generated by Django 6.0.1 on 2026-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_customuser_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('boost_type', models.CharField(choices=[('TURBO_MINING', 'Turbo Mining'), ('FREE_SPIN_PACK', 'Pack Tours Gratuits'), ('EXTRA_TASKS', 'Tâches Supplémentaires'), ('DOUBLE_REWARD', 'Gain Doublé'), ('WITHDRAWAL_PRIORITY', 'Retrait Prioritaire')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantité délivrée (ex: 5 tours)')),
                ('duration_hours', models.IntegerField(default=0, help_text='Durée en heures (0 = immédiat)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='extra_tasks_today',
            field=models.IntegerField(default=0, verbose_name="Tâches supplémentaires aujourd'hui"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_tier',
            field=models.IntegerField(default=0, verbose_name='Palier parrainage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_referrals',
            field=models.IntegerField(default=0, verbose_name='Total filleuls directs'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='turbo_mining_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Turbo minage jusqu'à"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('MINING_REWARD', 'Gain Minage'), ('TASK_REWARD', 'Gain Tâche'), ('VIP_PURCHASE', 'Achat VIP'), ('REFERRAL_BONUS', 'Bonus Parrainage'), ('DAILY_CHECKIN', 'Bonus Quotidien'), ('SPIN_WIN', 'Roue de la Fortune'), ('BOOST_PURCHASE', 'Achat Boost')], max_length=20),
        ),
    ]
