# Generated by Django 6.0.1 on 2026-05-29 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_boost_customuser_extra_tasks_today_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='fa-star', help_text='Classe FontAwesome', max_length=50)),
                ('condition_type', models.CharField(choices=[('TASKS_COMPLETED', 'Tâches complétées'), ('REFERRALS', 'Filleuls parrainés'), ('TOTAL_EARNED', 'Gains totaux'), ('CHECKIN_STREAK', 'Série check-in'), ('VIP_PURCHASE', 'Achat VIP'), ('DAYS_ACTIVE', 'Jours actifs')], max_length=30)),
                ('condition_value', models.IntegerField(help_text='Valeur à atteindre')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['condition_value'],
            },
        ),
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_type', models.CharField(choices=[('COMPLETE_TASKS', 'Compléter des tâches'), ('MINE', 'Lancer le minage'), ('SPIN_WHEEL', 'Tourner la roue'), ('CHECK_IN', 'Check-in quotidien'), ('VISIT', 'Visiter la plateforme')], max_length=30)),
                ('target', models.IntegerField(default=1, help_text='Objectif à atteindre')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['mission_type'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='trust_score',
            field=models.IntegerField(default=0, verbose_name='Score de confiance'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.ManyToManyField(blank=True, through='core.UserBadge', to='core.badge'),
        ),
        migrations.CreateModel(
            name='UserMissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailymission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission', 'date')},
            },
        ),
    ]
