# Generated by Django 6.0.1 on 2026-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_announcement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=True, verbose_name='Mode sombre'),
        ),
    ]
